---
include:
  - project: 'pipeline-components/org/config'
    ref: master
    file: pipeline.yml

test amd64:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm -v $(pwd):/code "${CI_REGISTRY_IMAGE}/${BUILD_ARCH}:${CI_COMMIT_SHA}" phpunit test/integrationTest.php

test amd64 defaultcmd:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/${BUILD_ARCH}:${CI_COMMIT_SHA}" --version
